"""add rbac tables

Revision ID: 6bc1a7347a04
Revises: 5c9d4e8f3a2b
Create Date: 2025-12-11 11:16:51.744927

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bc1a7347a04"
down_revision: str | None = "5c9d4e8f3a2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("module", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"], ["permissions.code"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_code"),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("assigned_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "assigned_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "role_id", "company_id", name="_user_role_company_uc"
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###

    # ### Seed data ###
    permissions_table = sa.table(
        "permissions",
        sa.column("code", sa.String),
        sa.column("module", sa.String),
        sa.column("description", sa.String),
    )

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("is_system", sa.Boolean),
        sa.column("description", sa.String),
    )

    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID),
        sa.column("permission_code", sa.String),
    )

    core_permissions = [
        # User management
        {"code": "user.read", "module": "core", "description": "Read user information"},
        {
            "code": "user.write.self",
            "module": "core",
            "description": "Update own user profile",
        },
        {
            "code": "user.write.all",
            "module": "core",
            "description": "Update any user profile",
        },
        {
            "code": "user.manage",
            "module": "core",
            "description": "Create, deactivate, and manage users",
        },
        # Company management
        {
            "code": "company.view",
            "module": "core",
            "description": "View company information",
        },
        {
            "code": "company.manage",
            "module": "core",
            "description": "Create and manage companies",
        },
        # Event management
        {
            "code": "event.read",
            "module": "core",
            "description": "View event information",
        },
        {
            "code": "event.write",
            "module": "core",
            "description": "Create and edit events",
        },
        {"code": "event.delete", "module": "core", "description": "Delete events"},
        # Expense management
        {"code": "expense.view", "module": "core", "description": "View expenses"},
        {"code": "expense.manage", "module": "core", "description": "Manage expenses"},
        # Integration & System
        {
            "code": "integration.use",
            "module": "core",
            "description": "Use integrations",
        },
        {
            "code": "integration.config",
            "module": "core",
            "description": "Configure integrations",
        },
        {
            "code": "system.admin",
            "module": "core",
            "description": "Full system administration",
        },
        {
            "code": "system.settings.read",
            "module": "core",
            "description": "Read system settings",
        },
        {
            "code": "system.settings.write",
            "module": "core",
            "description": "Write system settings",
        },
    ]

    op.bulk_insert(permissions_table, core_permissions)

    global_admin_role_id = uuid.uuid4()
    company_admin_role_id = uuid.uuid4()
    company_viewer_role_id = uuid.uuid4()

    default_roles = [
        {
            "id": global_admin_role_id,
            "name": "Global Admin",
            "is_system": True,
            "description": "Grants all permissions across the entire system.",
        },
        {
            "id": company_admin_role_id,
            "name": "Company Admin",
            "is_system": False,
            "description": "Grants administrative permissions for an assigned company.",
        },
        {
            "id": company_viewer_role_id,
            "name": "Company Viewer",
            "is_system": False,
            "description": "Grants read-only permissions for an assigned company.",
        },
    ]

    op.bulk_insert(roles_table, default_roles)

    # Assign permissions to roles
    global_admin_permissions = [p["code"] for p in core_permissions]
    company_admin_permissions = [
        "company.view",
        "company.manage",
        "expense.view",
        "expense.manage",
        "event.read",
        "event.write",
        "event.delete",
    ]
    company_viewer_permissions = [
        "company.view",
        "expense.view",
        "event.read",
    ]

    role_permissions_to_insert = []
    for perm_code in global_admin_permissions:
        role_permissions_to_insert.append(
            {"role_id": global_admin_role_id, "permission_code": perm_code}
        )

    for perm_code in company_admin_permissions:
        role_permissions_to_insert.append(
            {"role_id": company_admin_role_id, "permission_code": perm_code}
        )

    for perm_code in company_viewer_permissions:
        role_permissions_to_insert.append(
            {"role_id": company_viewer_role_id, "permission_code": perm_code}
        )

    op.bulk_insert(role_permissions_table, role_permissions_to_insert)

    # Migrate existing admins
    # We need to handle both string and UUID user IDs
    bind = op.get_bind()
    meta = sa.MetaData()
    meta.reflect(bind=bind, only=("users",))
    users_table = sa.Table("users", meta)

    user_roles_table = sa.table(
        "user_roles",
        sa.column("user_id", sa.UUID),
        sa.column("role_id", sa.UUID),
        sa.column("company_id", sa.UUID),
        sa.column("assigned_by_id", sa.UUID),
    )

    admin_users = bind.execute(
        sa.select(users_table).where(users_table.c.is_admin)
    ).fetchall()

    user_roles_to_insert = []
    for user in admin_users:
        user_id = user.id
        if isinstance(user_id, str):
            user_id = uuid.UUID(user_id)

        user_roles_to_insert.append(
            {
                "user_id": user_id,
                "role_id": global_admin_role_id,
                "company_id": None,
                "assigned_by_id": None,  # System migration
            }
        )

    if user_roles_to_insert:
        op.bulk_insert(user_roles_table, user_roles_to_insert)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.VARCHAR(length=5), nullable=False, server_default="user"),
    )
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
